### ISSUE TITLE
Pagination is present while having 5 books/authors on Books/Authors pages

### ISSUE THREAD

**Issue by zhivko-georgiev** [SSLibrary/MyLibrary#1]
Precondition:
- Make sure that there are 5 books/authors in the DB

Steps to reproduce:
1. Log in
2. Go to Books/Authors

Expected result:
No pagination is present on the page.

Actual result:
Pagination bar is present and is displaying "1" with no arrows around it. Please check the attached screenshot.
![i56 cimgpsh_orig](https://cloud.githubusercontent.com/assets/6910599/12063198/f22d4f6a-afb2-11e5-9210-86cfa823a1b4.png)

**Comment by VasilSokolov** [comment]
done
