### ISSUE TITLE
Having more than 5 books and click on 2nd page brings to wrong places

### ISSUE THREAD

**Issue by zhivko-georgiev** [SSLibrary/MyLibrary#2]
Precondition:
- Have more than 5 books in the DB

Steps to reproduce:
1. Log in
1.1 As admin
1.2 As regular user
2. Go to Books
3. Click over the second page in the pagination bar.

Expected results:
Second page containing books from 6th to 10th position in the DB.

Actual results:
- While logged as ADMIN
  Access Denied page is shown.
  ![i57 cimgpsh_orig](https://cloud.githubusercontent.com/assets/6910599/12063248/ff2b175a-afb3-11e5-9127-ee3e03a6712c.png)
- While logged as regular user.
  It bring us over the book history page.
  ![i58 cimgpsh_orig](https://cloud.githubusercontent.com/assets/6910599/12063252/08bf2a54-afb4-11e5-923c-0004867957d8.png)

_Note:_
The pagination in the Authors page works as expected while we are logged as Admin/User.

**Comment by VasilSokolov** [comment]
Незнам как си го направил ето го моя

![secondpage](https://cloud.githubusercontent.com/assets/7678066/12064977/20c9c6f8-afd8-11e5-9c94-ae335381a204.png)

**Comment by VasilSokolov** [comment]
?

**Comment by zhivko-georgiev** [comment]
Hello Vasil,

The issue was caused due to incorrect value of the URI populated into the pagination section.

Wrong value: uri="./books" 
Correct value: uri="../books/"

The issue is fixed and now the behavior is as per expected.

Regards,
Zhivko
